import { Link } from 'react-router-dom';
import GlassCard from '../components/ui/GlassCard';
import GlassButton from '../components/ui/GlassButton';
import GlassBadge from '../components/ui/GlassBadge';
import GradientText from '../components/ui/GradientText';
import Icon from '../components/ui/Icon';
import ImageLightbox from '../components/ui/ImageLightbox';
import IPhonePreviewWithDiscount from '../components/iphone/IPhonePreviewWithDiscount';
import ContactCaptureFeature from '../components/ContactCaptureFeature';
import SEO from '../components/SEO';
import StructuredData from '../components/StructuredData';
import { FRONTEND_URL } from '../utils/constants';

export default function Landing() {
  const features = [
    {
      icon: 'sms',
      title: 'Send Targeted SMS Campaigns',
      description: 'Create campaigns in minutes. Personalize with merge tags. Schedule for optimal send times. 98% open rates mean your messages actually get read.',
    },
    {
      icon: 'automation',
      title: 'Automate Customer Workflows',
      description: 'Welcome new customers automatically. Send birthday offers. Trigger messages based on orders or behavior. Set it once, let it run.',
    },
    {
      icon: 'analytics',
      title: 'Track Every Dollar',
      description: 'See delivery rates, opens, clicks, and conversions in real-time. Track revenue generated by each campaign. Make decisions based on actual results.',
    },
  ];

  const results = [
    {
      number: '98%',
      label: 'Open Rate',
      description: 'SMS messages are read within minutes',
      icon: 'analytics',
    },
    {
      number: '10x',
      label: 'Better ROI',
      description: 'Compared to email marketing',
      icon: 'growth',
    },
    {
      number: '3 min',
      label: 'Average Read Time',
      description: 'Customers read SMS instantly',
      icon: 'track',
    },
  ];

  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Astronote',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
      description: 'Free 14-day trial',
    },
    aggregateRating: {
      '@type': 'AggregateRating',
      ratingValue: '4.8',
      reviewCount: '150',
    },
  };

  const organizationData = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Astronote',
    url: FRONTEND_URL,
    logo: `${FRONTEND_URL}/Logo/astronote-logo.png`,
    description: 'SMS Marketing for Shopify. 98% open rates. Turn SMS into revenue with campaigns that actually get read. Customer data syncs automatically.',
    sameAs: [],
  };

  return (
    <>
      <SEO
        title="SMS Marketing That Actually Gets Read - 98% Open Rates | Astronote for Shopify"
        description="Stop losing sales to unread emails. SMS marketing with 98% open rates for Shopify stores. Customer data syncs automatically. Send discount codes that convert. Start free trial."
        path="/shopify"
        keywords="SMS marketing, Shopify SMS, text message marketing, SMS campaigns, Shopify integration, SMS automation, SMS analytics"
        jsonLd={[structuredData, organizationData]}
      />
      <StructuredData data={structuredData} />
      <main className="min-h-screen">
        {/* Hero Section */}
        <section className="relative pt-24 sm:pt-32 md:pt-36 pb-16 sm:pb-20 md:pb-24 px-4 sm:px-6 lg:px-8 overflow-hidden" aria-label="Hero section">
          {/* Background gradient with blobs */}
          <div className="absolute inset-0 bg-gradient-to-b from-bg-dark via-surface-dark to-bg-dark">
            <div className="absolute top-10 sm:top-20 right-10 sm:right-20 w-64 h-64 sm:w-96 sm:h-96 bg-ice-accent/10 rounded-full blur-3xl animate-float" />
            <div className="absolute bottom-10 sm:bottom-20 left-10 sm:left-20 w-64 h-64 sm:w-96 sm:h-96 bg-zoom-fuchsia/10 rounded-full blur-3xl animate-float" style={{ animationDelay: '2s' }} />
          </div>

          <div className="relative max-w-[1200px] mx-auto">
            <div className="text-center mb-12 sm:mb-16">
              <GlassBadge variant="ice" className="mb-4 sm:mb-6 inline-flex items-center gap-2 text-xs sm:text-sm">
                <Icon name="sms" size="sm" variant="ice" />
                <span>Stop Losing Sales to Unread Emails</span>
              </GlassBadge>
              
              <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold mb-4 sm:mb-6 leading-tight px-2">
                <span className="block mb-2">Turn Your Shopify Customers Into</span>
                <GradientText>Repeat Buyers</GradientText>
              </h1>
              
              <p className="text-lg sm:text-xl md:text-2xl text-border-subtle max-w-3xl mx-auto mb-3 sm:mb-4 leading-relaxed px-4">
                <strong className="text-primary-light">98% of your SMS messages get opened.</strong> Customers read them in under 3 minutes. 
                <span className="text-ice-accent"> Your customer data syncs automatically</span> from Shopify. 
                <span className="text-zoom-fuchsia"> Send discount codes that get redeemed.</span> 
                <strong className="text-primary-light"> Track revenue from every campaign.</strong>
              </p>

              <p className="text-base sm:text-lg text-border-subtle max-w-2xl mx-auto mb-6 sm:mb-10 px-4">
                Create campaigns in minutes. Automate workflows. See exactly how much revenue each message generates. 
                <strong className="text-primary-light"> All inside your Shopify admin—no switching platforms.</strong>
              </p>
              
              <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center items-center mb-8 sm:mb-12 px-4">
                <GlassButton variant="primary" size="lg" as={Link} to="/shopify/install" className="group w-full sm:w-auto">
                  <span className="flex items-center justify-center gap-2">
                    Install on Shopify
                    <Icon name="arrowRight" size="sm" className="group-hover:translate-x-1 transition-transform" />
                  </span>
                </GlassButton>
                <GlassButton variant="ghost" size="lg" as={Link} to="/shopify/how-it-works" className="w-full sm:w-auto">
                  How it works
                </GlassButton>
              </div>
              
              <div className="flex flex-wrap justify-center gap-4 sm:gap-6 text-xs sm:text-sm text-border-subtle px-4">
                <div className="flex items-center gap-2">
                  <Icon name="check" size="sm" variant="ice" />
                  <span>Free 14-day trial</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-zoom-fuchsia font-bold">98%</span>
                  <span>open rates</span>
                </div>
                <div className="flex items-center gap-2">
                  <Icon name="check" size="sm" variant="ice" />
                  <span>No credit card required</span>
                </div>
              </div>
            </div>

            {/* iPhone Preview with Discount Code */}
            <div className="mt-12 sm:mt-16 md:mt-20 px-4">
              <GlassCard variant="dark" className="p-6 sm:p-8">
                <div className="text-center mb-6 sm:mb-8">
                  <h3 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-2 sm:mb-3">See It In Action</h3>
                  <p className="text-sm sm:text-base text-border-subtle max-w-2xl mx-auto">
                    Here's how your SMS campaigns will look to customers. Real-time preview with discount codes and unsubscribe links included.
                  </p>
                </div>
                <div className="flex justify-center">
                  <IPhonePreviewWithDiscount
                    message="Hi {{first_name}}! Get 20% off your next order with code {{discount_code}}. Shop now at yourstore.com\n\nReply STOP to unsubscribe"
                    discountCode="SUMMER20"
                    firstName="Sarah"
                    unsubscribeToken="demo-token-123"
                  />
                </div>
              </GlassCard>
            </div>
          </div>
        </section>

        {/* Results Section */}
        <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 lg:px-8 bg-surface-dark/30">
          <div className="max-w-[1200px] mx-auto">
            <div className="text-center mb-8 sm:mb-12 px-4">
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 sm:mb-4">The Numbers Don't Lie</h2>
              <p className="text-base sm:text-lg text-border-subtle max-w-2xl mx-auto">
                While your emails sit unread, SMS messages get opened, clicked, and converted. 
                <strong className="text-primary-light"> This is why Shopify stores choose SMS over email every time.</strong>
              </p>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 sm:gap-8">
              {results.map((result, index) => (
                <GlassCard key={index} className="text-center p-6 sm:p-8 group hover:scale-[1.02] transition-all duration-300">
                  <div className="flex justify-center mb-4">
                    <div className="p-3 rounded-xl bg-ice-accent/20 group-hover:bg-ice-accent/30 transition-colors">
                      <Icon name={result.icon} size="lg" variant="ice" />
                    </div>
                  </div>
                  <div className="text-4xl sm:text-5xl font-bold text-zoom-fuchsia mb-3">{result.number}</div>
                  <h3 className="text-xl sm:text-2xl font-semibold mb-2">{result.label}</h3>
                  <p className="text-sm sm:text-base text-border-subtle">{result.description}</p>
                </GlassCard>
              ))}
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-[1200px] mx-auto">
            <div className="text-center mb-8 sm:mb-12 px-4">
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 sm:mb-4">Everything You Need to Succeed</h2>
              <p className="text-base sm:text-lg text-border-subtle max-w-2xl mx-auto">
                <strong className="text-primary-light">All the features that drive results.</strong> 
                Create campaigns, automate workflows, segment audiences, and track performance—all built to help you grow your Shopify store.
              </p>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 sm:gap-8">
              {features.map((feature, index) => (
                <GlassCard key={index} className="p-6 sm:p-8 text-center group hover:scale-[1.02] transition-all duration-300">
                  <div className="flex justify-center mb-4 sm:mb-6">
                    <div className="p-3 sm:p-4 rounded-xl bg-ice-accent/20 group-hover:bg-ice-accent/30 transition-colors">
                      <Icon name={feature.icon} size="xl" variant="ice" />
                    </div>
                  </div>
                  <h3 className="text-xl sm:text-2xl font-semibold mb-2 sm:mb-3">{feature.title}</h3>
                  <p className="text-sm sm:text-base text-border-subtle leading-relaxed">{feature.description}</p>
                </GlassCard>
              ))}
            </div>
          </div>
        </section>

        {/* Complete User Flow Section */}
        <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 lg:px-8 bg-surface-dark/30">
          <div className="max-w-[1400px] mx-auto">
            <div className="text-center mb-12 sm:mb-16 px-4">
              <GlassBadge variant="ice" className="mb-4 sm:mb-6 inline-flex items-center gap-2">
                <Icon name="workflow" size="sm" variant="ice" />
                <span>Complete User Journey</span>
              </GlassBadge>
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 sm:mb-4">See How Astronote Works</h2>
              <p className="text-base sm:text-lg md:text-xl text-border-subtle max-w-3xl mx-auto leading-relaxed">
                Follow the complete flow from installation to sending your first campaign. Every step is designed to be simple, intuitive, and powerful. 
                <strong className="text-primary-light"> Click any image to view in full size.</strong>
              </p>
            </div>

            {/* User Flow Steps */}
            <div className="space-y-16 sm:space-y-20 md:space-y-24">
              {/* Step 1: Campaigns Overview */}
              <div className="relative">
                <div className="flex items-center gap-4 mb-6">
                  <div className="flex-shrink-0 w-12 h-12 sm:w-16 sm:h-16 rounded-full bg-gradient-to-br from-ice-accent to-zoom-fuchsia flex items-center justify-center text-primary-dark font-bold text-lg sm:text-xl shadow-glow-ice">
                    1
                  </div>
                  <div>
                    <h3 className="text-2xl sm:text-3xl md:text-4xl font-bold text-primary-light">Manage All Your Campaigns</h3>
                    <p className="text-sm sm:text-base text-border-subtle mt-1">See performance, revenue, and engagement metrics at a glance</p>
                  </div>
                </div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8 items-center">
                  <div className="order-2 lg:order-1">
                    <GlassCard variant="ice" className="p-0 overflow-hidden">
                      <div className="relative bg-gradient-to-b from-neutral-surface-primary to-neutral-surface-secondary p-4">
                        <div className="mb-3 flex items-center gap-2">
                          <div className="flex gap-1.5">
                            <div className="w-3 h-3 rounded-full bg-red-400" />
                            <div className="w-3 h-3 rounded-full bg-yellow-400" />
                            <div className="w-3 h-3 rounded-full bg-green-400" />
                          </div>
                          <div className="flex-1 h-6 rounded bg-neutral-border/30" />
                        </div>
                        <div className="relative rounded-lg overflow-hidden shadow-glass-light-lg bg-white">
                          <ImageLightbox 
                            imageSrc="/images/campaigns.png" 
                            imageAlt="Campaigns Dashboard - View and manage all your SMS campaigns"
                            className="w-full"
                          >
                            <img 
                              src="/images/campaigns.png" 
                              alt="Campaigns Dashboard"
                              className="w-full h-auto object-contain transition-transform duration-500 hover:scale-105 cursor-pointer"
                              onError={(e) => {
                                e.target.style.display = 'none';
                              }}
                            />
                          </ImageLightbox>
                        </div>
                      </div>
                    </GlassCard>
                  </div>
                  <div className="order-1 lg:order-2 space-y-4">
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">View All Campaigns</h4>
                        <p className="text-sm sm:text-base text-border-subtle">See all your SMS campaigns in one place. Track revenue, opens, clicks, and conversions for each campaign.</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">Track Revenue & Performance</h4>
                        <p className="text-sm sm:text-base text-border-subtle">See exactly how much revenue each campaign generates. Monitor delivery rates, opens, and conversions in real-time.</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">Quick Actions</h4>
                        <p className="text-sm sm:text-base text-border-subtle">Edit, duplicate, pause, or delete campaigns with a single click. Manage everything efficiently.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Step 2: Create Campaign */}
              <div className="relative">
                <div className="flex items-center gap-4 mb-6">
                  <div className="flex-shrink-0 w-12 h-12 sm:w-16 sm:h-16 rounded-full bg-gradient-to-br from-ice-accent to-zoom-fuchsia flex items-center justify-center text-primary-dark font-bold text-lg sm:text-xl shadow-glow-ice">
                    2
                  </div>
                  <div>
                    <h3 className="text-2xl sm:text-3xl md:text-4xl font-bold text-primary-light">Create Campaigns That Convert</h3>
                    <p className="text-sm sm:text-base text-border-subtle mt-1">Write messages, add discount codes, and see exactly how they'll look to customers</p>
                  </div>
                </div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8 items-center">
                  <div className="order-2 lg:order-2">
                    <GlassCard variant="ice" className="p-0 overflow-hidden">
                      <div className="relative bg-gradient-to-b from-neutral-surface-primary to-neutral-surface-secondary p-4">
                        <div className="mb-3 flex items-center gap-2">
                          <div className="flex gap-1.5">
                            <div className="w-3 h-3 rounded-full bg-red-400" />
                            <div className="w-3 h-3 rounded-full bg-yellow-400" />
                            <div className="w-3 h-3 rounded-full bg-green-400" />
                          </div>
                          <div className="flex-1 h-6 rounded bg-neutral-border/30" />
                        </div>
                        <div className="relative rounded-lg overflow-hidden shadow-glass-light-lg bg-white">
                          <ImageLightbox 
                            imageSrc="/images/create_campaign.png" 
                            imageAlt="Create Campaign - Build targeted SMS campaigns with our intuitive builder"
                            className="w-full"
                          >
                            <img 
                              src="/images/create_campaign.png" 
                              alt="Create Campaign"
                              className="w-full h-auto object-contain transition-transform duration-500 hover:scale-105 cursor-pointer"
                              onError={(e) => {
                                e.target.style.display = 'none';
                              }}
                            />
                          </ImageLightbox>
                        </div>
                      </div>
                    </GlassCard>
                  </div>
                  <div className="order-1 lg:order-1 space-y-4">
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">Intuitive Campaign Builder</h4>
                        <p className="text-sm sm:text-base text-border-subtle">Write your message, preview it on iPhone, and add discount codes. See exactly how it will look to customers.</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">Personalize Messages</h4>
                        <p className="text-sm sm:text-base text-border-subtle">Use merge tags to personalize with customer names, order details, and custom variables for maximum engagement.</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">Schedule & Target</h4>
                        <p className="text-sm sm:text-base text-border-subtle">Schedule campaigns for optimal send times and target specific customer segments for better results.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Step 3: Reports & Analytics */}
              <div className="relative">
                <div className="flex items-center gap-4 mb-6">
                  <div className="flex-shrink-0 w-12 h-12 sm:w-16 sm:h-16 rounded-full bg-gradient-to-br from-ice-accent to-zoom-fuchsia flex items-center justify-center text-primary-dark font-bold text-lg sm:text-xl shadow-glow-ice">
                    3
                  </div>
                  <div>
                    <h3 className="text-2xl sm:text-3xl md:text-4xl font-bold text-primary-light">Track Revenue & ROI</h3>
                    <p className="text-sm sm:text-base text-border-subtle mt-1">See exactly how much revenue each campaign generates. Optimize for better results.</p>
                  </div>
                </div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8 items-center">
                  <div className="order-2 lg:order-1">
                    <GlassCard variant="ice" className="p-0 overflow-hidden">
                      <div className="relative bg-gradient-to-b from-neutral-surface-primary to-neutral-surface-secondary p-4">
                        <div className="mb-3 flex items-center gap-2">
                          <div className="flex gap-1.5">
                            <div className="w-3 h-3 rounded-full bg-red-400" />
                            <div className="w-3 h-3 rounded-full bg-yellow-400" />
                            <div className="w-3 h-3 rounded-full bg-green-400" />
                          </div>
                          <div className="flex-1 h-6 rounded bg-neutral-border/30" />
                        </div>
                        <div className="relative rounded-lg overflow-hidden shadow-glass-light-lg bg-white">
                          <ImageLightbox 
                            imageSrc="/images/reports.png" 
                            imageAlt="Reports & Analytics - Track campaign performance and ROI"
                            className="w-full"
                          >
                            <img 
                              src="/images/reports.png" 
                              alt="Reports & Analytics"
                              className="w-full h-auto object-contain transition-transform duration-500 hover:scale-105 cursor-pointer"
                              onError={(e) => {
                                e.target.style.display = 'none';
                              }}
                            />
                          </ImageLightbox>
                        </div>
                      </div>
                    </GlassCard>
                  </div>
                  <div className="order-1 lg:order-2 space-y-4">
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">Real-Time Analytics</h4>
                        <p className="text-sm sm:text-base text-border-subtle">Monitor delivery rates, open rates, click-through rates, and conversions as they happen.</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">Revenue Tracking</h4>
                        <p className="text-sm sm:text-base text-border-subtle">See exactly how much revenue each campaign generates. Track ROI, optimize for better results, and make data-driven decisions.</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="md" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-lg sm:text-xl font-semibold text-primary-light mb-1">Export & Share</h4>
                        <p className="text-sm sm:text-base text-border-subtle">Export detailed reports to CSV, share insights with your team, and make data-driven decisions.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Shopify Banners Section */}
        <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-[1400px] mx-auto">
            <div className="text-center mb-12 sm:mb-16 px-4">
              <GlassBadge variant="ice" className="mb-4 sm:mb-6 inline-flex items-center gap-2">
                <Icon name="integration" size="sm" variant="ice" />
                <span>Shopify Store Integration</span>
              </GlassBadge>
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 sm:mb-4">Grow Your SMS List Where Customers Already Shop</h2>
              <p className="text-base sm:text-lg md:text-xl text-border-subtle max-w-3xl mx-auto leading-relaxed">
                <strong className="text-primary-light">Beautiful opt-in forms that match your store design.</strong> 
                Customers subscribe right on your storefront—no redirects, no friction. 
                <strong className="text-primary-light"> All phone numbers sync automatically to your dashboard.</strong>
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 sm:gap-8">
              {/* Banner */}
              <div className="group">
                <GlassCard variant="ice" className="p-0 overflow-hidden hover:scale-[1.02] transition-all duration-300">
                  <div className="relative bg-gradient-to-b from-neutral-surface-primary to-neutral-surface-secondary p-4">
                    <div className="mb-3 flex items-center gap-2">
                      <div className="flex gap-1.5">
                        <div className="w-3 h-3 rounded-full bg-red-400" />
                        <div className="w-3 h-3 rounded-full bg-yellow-400" />
                        <div className="w-3 h-3 rounded-full bg-green-400" />
                      </div>
                      <div className="flex-1 h-6 rounded bg-neutral-border/30" />
                    </div>
                    <div className="relative rounded-lg overflow-hidden shadow-glass-light-lg bg-white">
                      <ImageLightbox 
                        imageSrc="/banner/banner.png" 
                        imageAlt="SMS Opt-in Banner - Beautiful banner that appears on your Shopify storefront"
                        className="w-full"
                      >
                        <img 
                          src="/banner/banner.png" 
                          alt="SMS Opt-in Banner"
                          className="w-full h-auto object-contain transition-transform duration-500 group-hover:scale-105 cursor-pointer"
                          onError={(e) => {
                            e.target.style.display = 'none';
                          }}
                        />
                      </ImageLightbox>
                    </div>
                  </div>
                  <div className="p-4 sm:p-6">
                    <h3 className="text-lg sm:text-xl font-semibold mb-2 text-primary-light">Storefront Banner</h3>
                    <p className="text-sm sm:text-base text-border-subtle mb-3">
                      A beautiful, non-intrusive banner that appears on your store pages. Fully customizable colors, text, and placement to match your brand.
                    </p>
                    <div className="flex flex-wrap gap-2">
                      <GlassBadge variant="ice" size="sm">Customizable</GlassBadge>
                      <GlassBadge variant="ice" size="sm">Theme Integration</GlassBadge>
                      <GlassBadge variant="ice" size="sm">Mobile Responsive</GlassBadge>
                    </div>
                  </div>
                </GlassCard>
              </div>

              {/* Modal */}
              <div className="group">
                <GlassCard variant="ice" className="p-0 overflow-hidden hover:scale-[1.02] transition-all duration-300">
                  <div className="relative bg-gradient-to-b from-neutral-surface-primary to-neutral-surface-secondary p-4">
                    <div className="mb-3 flex items-center gap-2">
                      <div className="flex gap-1.5">
                        <div className="w-3 h-3 rounded-full bg-red-400" />
                        <div className="w-3 h-3 rounded-full bg-yellow-400" />
                        <div className="w-3 h-3 rounded-full bg-green-400" />
                      </div>
                      <div className="flex-1 h-6 rounded bg-neutral-border/30" />
                    </div>
                    <div className="relative rounded-lg overflow-hidden shadow-glass-light-lg bg-white">
                      <ImageLightbox 
                        imageSrc="/banner/modal.png" 
                        imageAlt="SMS Opt-in Modal - Elegant popup modal for collecting phone numbers"
                        className="w-full"
                      >
                        <img 
                          src="/banner/modal.png" 
                          alt="SMS Opt-in Modal"
                          className="w-full h-auto object-contain transition-transform duration-500 group-hover:scale-105 cursor-pointer"
                          onError={(e) => {
                            e.target.style.display = 'none';
                          }}
                        />
                      </ImageLightbox>
                    </div>
                  </div>
                  <div className="p-4 sm:p-6">
                    <h3 className="text-lg sm:text-xl font-semibold mb-2 text-primary-light">Opt-in Modal</h3>
                    <p className="text-sm sm:text-base text-border-subtle mb-3">
                      An elegant popup modal that appears when customers visit your store. Perfect for capturing attention and growing your SMS list quickly.
                    </p>
                    <div className="flex flex-wrap gap-2">
                      <GlassBadge variant="ice" size="sm">Popup Modal</GlassBadge>
                      <GlassBadge variant="ice" size="sm">High Conversion</GlassBadge>
                      <GlassBadge variant="ice" size="sm">GDPR Compliant</GlassBadge>
                    </div>
                  </div>
                </GlassCard>
              </div>
            </div>

            <div className="mt-8 sm:mt-12">
              <GlassCard variant="dark" className="p-6 sm:p-8">
                <div className="flex flex-col md:flex-row items-start gap-4 md:gap-6">
                  <div className="flex-shrink-0">
                    <div className="p-3 sm:p-4 rounded-xl bg-ice-accent/20">
                      <Icon name="integration" size="xl" variant="ice" />
                    </div>
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl sm:text-2xl font-bold text-primary-light mb-3">Seamless Integration</h3>
                    <p className="text-base sm:text-lg text-border-subtle mb-4 leading-relaxed">
                      Both the banner and modal integrate perfectly with your Shopify store theme. Customize colors, fonts, and positioning to match your brand. 
                      <strong className="text-primary-light"> All phone numbers sync automatically to your dashboard—no manual work required.</strong> 
                      Start sending campaigns to new subscribers immediately.
                    </p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      <div className="flex items-start gap-2">
                        <Icon name="check" size="sm" variant="ice" className="mt-1 flex-shrink-0" />
                        <span className="text-sm text-border-subtle">Automatic contact sync</span>
                      </div>
                      <div className="flex items-start gap-2">
                        <Icon name="check" size="sm" variant="ice" className="mt-1 flex-shrink-0" />
                        <span className="text-sm text-border-subtle">GDPR-compliant opt-in</span>
                      </div>
                      <div className="flex items-start gap-2">
                        <Icon name="check" size="sm" variant="ice" className="mt-1 flex-shrink-0" />
                        <span className="text-sm text-border-subtle">Mobile-responsive design</span>
                      </div>
                      <div className="flex items-start gap-2">
                        <Icon name="check" size="sm" variant="ice" className="mt-1 flex-shrink-0" />
                        <span className="text-sm text-border-subtle">Customizable branding</span>
                      </div>
                    </div>
                  </div>
                </div>
              </GlassCard>
            </div>
          </div>
        </section>

        {/* How It Works - Simple 3 Steps */}
        <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-[1200px] mx-auto">
            <div className="text-center mb-8 sm:mb-12 px-4">
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 sm:mb-4">Get Started in 3 Steps</h2>
              <p className="text-base sm:text-lg text-border-subtle max-w-2xl mx-auto">
                <strong className="text-primary-light">Start sending campaigns in minutes.</strong> 
                Your customer data syncs automatically. No technical knowledge required.
              </p>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 sm:gap-8">
              <GlassCard className="text-center p-6 sm:p-8 relative">
                <div className="absolute -top-3 sm:-top-4 -left-3 sm:-left-4 w-10 h-10 sm:w-12 sm:h-12 rounded-full bg-ice-accent text-primary-dark flex items-center justify-center font-bold text-base sm:text-lg shadow-glow-ice">
                  1
                </div>
                <div className="mt-4 sm:mt-4 mb-4 sm:mb-6 flex justify-center">
                  <div className="p-3 sm:p-4 rounded-xl bg-ice-accent/20">
                    <Icon name="connect" size="xl" variant="ice" />
                  </div>
                </div>
                <h3 className="text-xl sm:text-2xl font-semibold mb-2 sm:mb-3">Install & Connect</h3>
                <p className="text-sm sm:text-base text-border-subtle leading-relaxed">
                  Install Astronote from Shopify App Store. Connect your store in one click.
                </p>
              </GlassCard>

              <GlassCard className="text-center p-6 sm:p-8 relative">
                <div className="absolute -top-3 sm:-top-4 -left-3 sm:-left-4 w-10 h-10 sm:w-12 sm:h-12 rounded-full bg-ice-accent text-primary-dark flex items-center justify-center font-bold text-base sm:text-lg shadow-glow-ice">
                  2
                </div>
                <div className="mt-4 sm:mt-4 mb-4 sm:mb-6 flex justify-center">
                  <div className="p-3 sm:p-4 rounded-xl bg-ice-accent/20">
                    <Icon name="campaign" size="xl" variant="ice" />
                  </div>
                </div>
                <h3 className="text-xl sm:text-2xl font-semibold mb-2 sm:mb-3">Create Campaign</h3>
                <p className="text-sm sm:text-base text-border-subtle leading-relaxed">
                  Write your message, preview it on iPhone, and add discount codes.
                </p>
              </GlassCard>

              <GlassCard className="text-center p-6 sm:p-8 relative">
                <div className="absolute -top-3 sm:-top-4 -left-3 sm:-left-4 w-10 h-10 sm:w-12 sm:h-12 rounded-full bg-ice-accent text-primary-dark flex items-center justify-center font-bold text-base sm:text-lg shadow-glow-ice">
                  3
                </div>
                <div className="mt-4 sm:mt-4 mb-4 sm:mb-6 flex justify-center">
                  <div className="p-3 sm:p-4 rounded-xl bg-ice-accent/20">
                    <Icon name="send" size="xl" variant="ice" />
                  </div>
                </div>
                <h3 className="text-xl sm:text-2xl font-semibold mb-2 sm:mb-3">Send & Track</h3>
                <p className="text-sm sm:text-base text-border-subtle leading-relaxed">
                  Send immediately or schedule for later. Track opens and conversions.
                </p>
              </GlassCard>
            </div>
          </div>
        </section>

        {/* How We Capture Contacts Section */}
        <ContactCaptureFeature />

        {/* GDPR Compliance Section */}
        <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-[1200px] mx-auto">
            <GlassCard variant="ice" className="p-6 sm:p-8 md:p-12">
              <div className="flex flex-col md:flex-row items-start gap-6 sm:gap-8">
                <div className="flex-shrink-0">
                  <div className="p-3 sm:p-4 rounded-xl bg-ice-accent/20">
                    <Icon name="compliance" size="xl" variant="ice" />
                  </div>
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-3 sm:mb-4">
                    <Icon name="check" size="md" variant="ice" />
                    <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold">GDPR Compliant</h2>
                  </div>
                  <p className="text-base sm:text-lg md:text-xl text-border-subtle mb-4 sm:mb-6 leading-relaxed">
                    Astronote is fully compliant with GDPR and all international data protection regulations. 
                    Your customers' data is secure, and you can market with confidence.
                  </p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="sm" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-sm sm:text-base font-semibold text-primary-light mb-1">Opt-in Management</h4>
                        <p className="text-xs sm:text-sm text-border-subtle">Customers must explicitly consent to receive SMS messages</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="sm" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-sm sm:text-base font-semibold text-primary-light mb-1">Easy Unsubscribe</h4>
                        <p className="text-xs sm:text-sm text-border-subtle">One-click unsubscribe in every message</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="sm" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-sm sm:text-base font-semibold text-primary-light mb-1">Data Protection</h4>
                        <p className="text-xs sm:text-sm text-border-subtle">All customer data is encrypted and securely stored</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <Icon name="check" size="sm" variant="ice" className="mt-1 flex-shrink-0" />
                      <div>
                        <h4 className="text-sm sm:text-base font-semibold text-primary-light mb-1">Compliance Reporting</h4>
                        <p className="text-xs sm:text-sm text-border-subtle">Track consent and opt-out rates automatically</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </GlassCard>
          </div>
        </section>

        {/* Social Proof / Metrics */}
        <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 lg:px-8 bg-surface-dark/30">
          <div className="max-w-[1200px] mx-auto">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 sm:gap-8 text-center">
              <div>
                <div className="text-4xl sm:text-5xl font-bold text-zoom-fuchsia mb-2">10K+</div>
                <p className="text-sm sm:text-base text-border-subtle">Active Stores</p>
              </div>
              <div>
                <div className="text-4xl sm:text-5xl font-bold text-zoom-fuchsia mb-2">50M+</div>
                <p className="text-sm sm:text-base text-border-subtle">Messages Sent</p>
              </div>
              <div>
                <div className="text-4xl sm:text-5xl font-bold text-zoom-fuchsia mb-2">98%</div>
                <p className="text-sm sm:text-base text-border-subtle">Average Open Rate</p>
              </div>
            </div>
          </div>
        </section>

        {/* Final CTA */}
        <section className="py-16 sm:py-20 md:py-24 px-4 sm:px-6 bg-gradient-to-b from-surface-dark to-bg-dark relative overflow-hidden">
          <div className="absolute inset-0">
            <div className="absolute top-0 left-1/4 w-64 h-64 sm:w-96 sm:h-96 bg-ice-accent/10 rounded-full blur-3xl animate-float" />
            <div className="absolute bottom-0 right-1/4 w-64 h-64 sm:w-96 sm:h-96 bg-zoom-fuchsia/10 rounded-full blur-3xl animate-float" style={{ animationDelay: '2s' }} />
          </div>
          <div className="relative max-w-[800px] mx-auto text-center">
            <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-4 sm:mb-6 px-4">Stop Waiting. Start Growing.</h2>
            <p className="text-base sm:text-lg md:text-xl text-border-subtle mb-6 sm:mb-8 leading-relaxed px-4">
              <strong className="text-primary-light">Your customers are on their phones right now.</strong> 
              While you're sending emails that get ignored, your competitors are using SMS to drive sales. 
              <strong className="text-primary-light"> Start your free trial today—no credit card required.</strong>
            </p>
            <GlassButton variant="primary" size="lg" as={Link} to="/shopify/install" className="group w-full sm:w-auto px-4">
              <span className="flex items-center justify-center gap-2">
                Start Free Trial
                <Icon name="arrowRight" size="sm" className="group-hover:translate-x-1 transition-transform" />
              </span>
            </GlassButton>
            <p className="text-xs sm:text-sm text-border-subtle mt-4 px-4">No credit card required • 14-day free trial</p>
          </div>
        </section>
      </main>
    </>
  );
}
